<?xml version="1.0" encoding="utf-8"?><Database Name="StudentBazaDanych" Class="StudentDataContextLINQ" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=S219-4\sqlexpress;Initial Catalog=StudentBazaDanych;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="StudentBazaDanychConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.StudentTabela" Member="StudentTabelas">
    <Type Name="StudentTabela">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Imię" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nazwisko" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Wiek" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>